export const routes = {
  login: "/login",
  dashboard: "/dashboard",
  storesDashboard: "/stores",
  projects: "/projects",
  assets: "/assets",
  allocations: "/allocations",
  dailyLogs: "/daily-logs",
  reference: "/reference",
  scopeItems: "/reference/scope-items",
  laborNorms: "/reference/labor-norms",
  inventoryManagement: "/reference/material-catalog",
  materialCatalog: "/reference/material-catalog",
  sheqTemplates: "/reference/sheq-templates",
  teamAssignments: "/operations/team-assignments",
  siteManagerDashboard: "/operations/site-manager",
  siteManagerProjects: "/operations/site-manager/projects",
  siteManagerTimesheets: "/operations/site-manager/timesheets",
  financeDashboard: "/finance",
  financeBudgets: "/finance/budgets",
  financeCostCodes: "/finance/cost-codes",
  financePurchaseOrders: "/finance/purchase-orders",
  financeGrns: "/finance/grns",
  financeInvoices: "/finance/invoices"
};
